// Localization Dictionary
const TRANSLATIONS = {
  en: {
    "eyebrow": "GitHub Pages Ready",
    "title": "Turn any avatar into the Google-style framed profile picture.",
    "hero-copy": "Upload an image, preview the result instantly in your browser, and download the generated PNG. The output uses the calibrated four-color ring layout and the thinner 4% color ring plus 2% white spacer.",
    "panel-upload-header": "Upload Avatar",
    "panel-upload-copy": "Images are processed locally in your browser. Nothing is sent to a server.",
    "upload-title": "Choose an avatar",
    "upload-subtitle": "or drag & drop here (PNG, JPG, WEBP, BMP)",
    "presets-title": "Or use a preset",
    "ring-settings-header": "Ring Settings",
    "label-ring-width": "Ring Thickness",
    "label-gap-width": "White Spacer",
    "label-palette": "Color Palette",
    "palette-classic": "Google Classic",
    "palette-monochrome": "Monochrome",
    "palette-neon": "Neon",
    "palette-pastel": "Pastel",
    "avatar-settings-header": "Avatar Adjustments",
    "label-zoom": "Avatar Zoom",
    "label-offset-x": "X Offset",
    "label-offset-y": "Y Offset",
    "btn-download": "Download PNG",
    "btn-reset": "Reset Settings",
    "status-waiting": "Waiting for an image.",
    "status-rendering": "Rendering avatar...",
    "status-loaded-err": "Please choose an image file.",
    "status-error": "This image could not be loaded.",
    "preview-original": "Original",
    "preview-generated": "Generated",
    "placeholder-original": "Your uploaded image will appear here.",
    "placeholder-generated": "The generated avatar will appear here.",
    "footer-created-by": "Created by",
    "footer-thanks": "Thanks to the original creator",
    "footer-announcement": "Some code was generated by"
  },
  zh: {
    "eyebrow": "支持 GitHub Pages 部署",
    "title": "让任意头像拥有Google风格的彩环相框",
    "hero-copy": "上传图片，在浏览器中实时预览生成效果，并一键下载导出的 PNG 图像。默认采用精准校对的 Google 四色彩环比例与微调参数。",
    "panel-upload-header": "上传头像",
    "panel-upload-copy": "所有图像均在浏览器本地处理，绝对不会上传到服务器。",
    "upload-title": "选择头像文件",
    "upload-subtitle": "或将文件拖拽至此 (PNG, JPG, WEBP, BMP)",
    "presets-title": "或选择预设头像测试",
    "ring-settings-header": "彩环相框设置",
    "label-ring-width": "彩环粗细",
    "label-gap-width": "留白间距",
    "label-palette": "彩环配色",
    "palette-classic": "Google经典",
    "palette-monochrome": "黑白极简",
    "palette-neon": "赛博霓虹",
    "palette-pastel": "马卡龙粉",
    "avatar-settings-header": "头像位置调整",
    "label-zoom": "头像缩放",
    "label-offset-x": "水平偏移",
    "label-offset-y": "垂直偏移",
    "btn-download": "下载 PNG",
    "btn-reset": "重置设置",
    "status-waiting": "等待选择或上传头像图片。",
    "status-rendering": "正在生成头像...",
    "status-loaded-err": "请选择图片文件格式。",
    "status-error": "图片加载失败，请重试。",
    "preview-original": "原始头像",
    "preview-generated": "生成效果",
    "placeholder-original": "您上传的原始头像将在此处显示。",
    "placeholder-generated": "生成的Google彩环头像将在此处显示。",
    "footer-created-by": "作者",
    "footer-thanks": "特别鸣谢原作者",
    "footer-announcement": "Gen-AI参与编写"
  }
};

// Color Ring Palettes
const PALETTES = {
  classic: [
    { color: "#EA4335", start: 206, end: 314 }, // red
    { color: "#4285F4", start: 314, end: 408 }, // blue
    { color: "#34A853", start: 48, end: 138 },  // green
    { color: "#FBBC05", start: 138, end: 206 }  // yellow
  ],
  monochrome: [
    { color: "#1F2937", start: 206, end: 314 },
    { color: "#4B5563", start: 314, end: 408 },
    { color: "#9CA3AF", start: 48, end: 138 },
    { color: "#D1D5DB", start: 138, end: 206 }
  ],
  neon: [
    { color: "#FF007F", start: 206, end: 314 }, // hot pink
    { color: "#00F0FF", start: 314, end: 408 }, // electric blue
    { color: "#39FF14", start: 48, end: 138 },  // neon green
    { color: "#FFEF00", start: 138, end: 206 }  // neon yellow
  ],
  pastel: [
    { color: "#FFB3BA", start: 206, end: 314 }, // pastel pink
    { color: "#BAE1FF", start: 314, end: 408 }, // pastel blue
    { color: "#BFFCC6", start: 48, end: 138 },  // pastel green
    { color: "#FFFFBA", start: 138, end: 206 }  // pastel yellow
  ]
};

// UI Elements
const fileInput = document.getElementById("file-input");
const dropZone = document.getElementById("drop-zone");
const downloadButton = document.getElementById("download-button");
const resetButton = document.getElementById("reset-button");
const status = document.getElementById("status");
const inputPreview = document.getElementById("input-preview");
const inputPlaceholder = document.getElementById("input-placeholder");
const outputCanvas = document.getElementById("output-canvas");
const outputPlaceholder = document.getElementById("output-placeholder");
const presetsContainer = document.getElementById("presets-container");

// Controls Elements
const ringWidthInput = document.getElementById("ring-width-input");
const ringWidthVal = document.getElementById("ring-width-val");
const gapWidthInput = document.getElementById("gap-width-input");
const gapWidthVal = document.getElementById("gap-width-val");
const zoomInput = document.getElementById("zoom-input");
const zoomVal = document.getElementById("zoom-val");
const offsetXInput = document.getElementById("offset-x-input");
const offsetXVal = document.getElementById("offset-x-val");
const offsetYInput = document.getElementById("offset-y-input");
const offsetYVal = document.getElementById("offset-y-val");
const paletteBtns = document.querySelectorAll(".palette-btn");

// Header Elements
const langToggle = document.getElementById("lang-toggle");
const themeToggle = document.getElementById("theme-toggle");

// App State
let currentLang = localStorage.getItem("g-avatar-lang") || "en";
let currentTheme = localStorage.getItem("g-avatar-theme") || "light";
let activeImage = null; // Can be Image or Canvas element
let outputDataUrl = "";
let selectedPalette = "classic";

// Set initial page state
document.documentElement.setAttribute("data-theme", currentTheme);
updateTranslations();
initThemeUI();

// ----------------------------------------------------
// TRANSLATION & THEME MANAGEMENT
// ----------------------------------------------------

function updateTranslations() {
  // Translate static data-i18n attributes
  document.querySelectorAll("[data-i18n]").forEach(element => {
    const key = element.getAttribute("data-i18n");
    if (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key]) {
      if (element.tagName === "INPUT" && element.placeholder) {
        element.placeholder = TRANSLATIONS[currentLang][key];
      } else {
        element.textContent = TRANSLATIONS[currentLang][key];
      }
    }
  });

  // Update Language Button label
  langToggle.querySelector(".lang-text").textContent = currentLang === "en" ? "ZH" : "EN";
  langToggle.title = currentLang === "en" ? "切换至中文" : "Switch to English";

  // Re-translate status bar if active
  if (!activeImage) {
    setStatus(TRANSLATIONS[currentLang]["status-waiting"]);
  } else {
    // Re-render to update the status text in the correct language
    renderAvatar(activeImage);
  }
}

function setStatus(message) {
  status.textContent = message;
}

// Toggle language
langToggle.addEventListener("click", () => {
  currentLang = currentLang === "en" ? "zh" : "en";
  localStorage.setItem("g-avatar-lang", currentLang);
  updateTranslations();
});

// Theme Toggle logic
function initThemeUI() {
  // Check if system prefers dark and no theme is stored
  if (!localStorage.getItem("g-avatar-theme") && window.matchMedia("(prefers-color-scheme: dark)").matches) {
    currentTheme = "dark";
    document.documentElement.setAttribute("data-theme", "dark");
  }
}

themeToggle.addEventListener("click", () => {
  currentTheme = currentTheme === "light" ? "dark" : "light";
  document.documentElement.setAttribute("data-theme", currentTheme);
  localStorage.setItem("g-avatar-theme", currentTheme);
});

// ----------------------------------------------------
// CANVAS RENDERING LOGIC
// ----------------------------------------------------

function drawRing(ctx, size, borderWidth) {
  const center = size / 2;
  const radius = center - borderWidth / 2;

  ctx.save();
  ctx.lineWidth = borderWidth;
  ctx.lineCap = "butt";

  const segments = PALETTES[selectedPalette] || PALETTES.classic;

  segments.forEach((segment) => {
    ctx.beginPath();
    ctx.strokeStyle = segment.color;
    ctx.arc(
      center,
      center,
      radius,
      (segment.start * Math.PI) / 180,
      (segment.end * Math.PI) / 180,
      false
    );
    ctx.stroke();
  });

  ctx.restore();
}

function drawCircularAvatar(ctx, image, size, borderWidth, gapWidth) {
  const avatarDiameter = size - 2 * (borderWidth + gapWidth);
  const avatarX = borderWidth + gapWidth;
  const avatarY = borderWidth + gapWidth;

  // Read zoom & offset adjustments
  const zoomFactor = parseFloat(zoomInput.value) / 100;
  const offsetXPercent = parseFloat(offsetXInput.value) / 100;
  const offsetYPercent = parseFloat(offsetYInput.value) / 100;

  // Source clipping bounds
  const minDim = Math.min(image.width, image.height);
  const sourceCropSize = minDim / zoomFactor;

  // Panning logic: offset is scaled relative to the available scroll range
  const maxShiftX = (image.width - sourceCropSize) / 2;
  const maxShiftY = (image.height - sourceCropSize) / 2;
  
  // Calculate crop coordinates on the source image
  const cropX = (image.width - sourceCropSize) / 2 + (offsetXPercent * image.width);
  const cropY = (image.height - sourceCropSize) / 2 + (offsetYPercent * image.height);

  ctx.save();
  ctx.beginPath();
  ctx.arc(size / 2, size / 2, avatarDiameter / 2, 0, Math.PI * 2);
  ctx.clip();
  
  // Draw avatar
  ctx.drawImage(
    image,
    cropX,
    cropY,
    sourceCropSize,
    sourceCropSize,
    avatarX,
    avatarY,
    avatarDiameter,
    avatarDiameter
  );
  ctx.restore();
}

function renderAvatar(image) {
  if (!image) return;

  const outputSize = Math.min(image.width, image.height);
  
  // Ratios
  const borderRatio = parseFloat(ringWidthInput.value) / 100;
  const gapRatio = parseFloat(gapWidthInput.value) / 100;

  const borderWidth = Math.max(1, Math.round(outputSize * borderRatio));
  const gapWidth = Math.max(0, Math.round(outputSize * gapRatio));

  outputCanvas.width = outputSize;
  outputCanvas.height = outputSize;
  outputCanvas.style.display = "block";
  outputPlaceholder.style.display = "none";

  const ctx = outputCanvas.getContext("2d");
  ctx.clearRect(0, 0, outputSize, outputSize);

  // 1. Draw Google Color Ring
  drawRing(ctx, outputSize, borderWidth);

  // 2. Draw White Spacer Background Disk
  ctx.fillStyle = "#FFFFFF";
  ctx.beginPath();
  ctx.arc(
    outputSize / 2,
    outputSize / 2,
    outputSize / 2 - borderWidth,
    0,
    Math.PI * 2
  );
  ctx.fill();

  // 3. Draw cropped, zoomed, and offset avatar
  drawCircularAvatar(ctx, image, outputSize, borderWidth, gapWidth);

  // 4. Update data export url & enable download
  try {
    outputDataUrl = outputCanvas.toDataURL("image/png");
    downloadButton.disabled = false;

    // 5. Update Status Text (localized)
    if (currentLang === "en") {
      setStatus(`Generated ${outputSize}x${outputSize} PNG with a ${borderWidth}px color ring and ${gapWidth}px white spacer.`);
    } else {
      setStatus(`已生成 ${outputSize}x${outputSize} 像素的 PNG 图像（含 ${borderWidth}px 彩环与 ${gapWidth}px 留白）。`);
    }
  } catch (err) {
    console.warn("Canvas export blocked by CORS policy:", err);
    outputDataUrl = "";
    downloadButton.disabled = true;

    if (currentLang === "en") {
      setStatus("CORS restriction on the preset image prevents direct download. Please upload an image manually to download.");
    } else {
      setStatus("受限于预设图片的跨域策略（CORS），无法直接下载该头像。请手动上传本地图片以支持导出下载。");
    }
  }
}

// ----------------------------------------------------
// EVENT BINDINGS FOR SLIDERS
// ----------------------------------------------------

function updateSliderValues() {
  ringWidthVal.textContent = `${parseFloat(ringWidthInput.value).toFixed(1)}%`;
  gapWidthVal.textContent = `${parseFloat(gapWidthInput.value).toFixed(1)}%`;
  zoomVal.textContent = `${zoomInput.value}%`;
  offsetXVal.textContent = `${offsetXInput.value}%`;
  offsetYVal.textContent = `${offsetYInput.value}%`;
}

// Listen to sliders
[ringWidthInput, gapWidthInput, zoomInput, offsetXInput, offsetYInput].forEach(input => {
  input.addEventListener("input", () => {
    updateSliderValues();
    if (activeImage) {
      renderAvatar(activeImage);
    }
  });
});

// Palette buttons
paletteBtns.forEach(btn => {
  btn.addEventListener("click", () => {
    paletteBtns.forEach(b => b.classList.remove("active"));
    btn.classList.add("active");
    selectedPalette = btn.getAttribute("data-palette");
    if (activeImage) {
      renderAvatar(activeImage);
    }
  });
});

// Reset controls
resetButton.addEventListener("click", () => {
  ringWidthInput.value = 4;
  gapWidthInput.value = 2;
  zoomInput.value = 100;
  offsetXInput.value = 0;
  offsetYInput.value = 0;
  
  // Reset active palette
  paletteBtns.forEach(b => b.classList.remove("active"));
  document.querySelector('.palette-btn[data-palette="classic"]').classList.add("active");
  selectedPalette = "classic";

  updateSliderValues();
  if (activeImage) {
    renderAvatar(activeImage);
  }
});

// Download Action
downloadButton.addEventListener("click", () => {
  if (!outputDataUrl) return;

  const link = document.createElement("a");
  link.href = outputDataUrl;
  link.download = "google-avatar-frame.png";
  link.click();
});

// ----------------------------------------------------
// FILE UPLOAD AND DRAG-AND-DROP HANDLERS
// ----------------------------------------------------

function handleFile(file) {
  if (!file) return;

  if (!file.type.startsWith("image/")) {
    setStatus(TRANSLATIONS[currentLang]["status-loaded-err"]);
    return;
  }

  setStatus(TRANSLATIONS[currentLang]["status-rendering"]);
  const fileUrl = URL.createObjectURL(file);
  const image = new Image();

  image.onload = () => {
    // Clear active preset buttons styling
    document.querySelectorAll(".preset-item").forEach(item => item.classList.remove("active"));

    inputPreview.src = fileUrl;
    inputPreview.style.display = "block";
    inputPlaceholder.style.display = "none";
    
    activeImage = image;
    renderAvatar(image);
    URL.revokeObjectURL(fileUrl);
  };

  image.onerror = () => {
    URL.revokeObjectURL(fileUrl);
    setStatus(TRANSLATIONS[currentLang]["status-error"]);
  };

  image.src = fileUrl;
}

fileInput.addEventListener("change", (event) => {
  const [file] = event.target.files;
  handleFile(file);
});

// Drag and drop event listeners
["dragenter", "dragover"].forEach(eventName => {
  dropZone.addEventListener(eventName, (e) => {
    e.preventDefault();
    dropZone.classList.add("dragover");
  }, false);
});

["dragleave", "drop"].forEach(eventName => {
  dropZone.addEventListener(eventName, (e) => {
    e.preventDefault();
    dropZone.classList.remove("dragover");
  }, false);
});

dropZone.addEventListener("drop", (e) => {
  const dt = e.dataTransfer;
  const file = dt.files[0];
  handleFile(file);
}, false);

// ----------------------------------------------------
// PRESETS GENERATOR (SINGLE REMOTE IMAGE PRESET)
// ----------------------------------------------------

const PRESET_URL = "https://img.998315.xyz/api/Pic/avatar.jpg";

function initPresets() {
  const btn = document.createElement("button");
  btn.className = "preset-item active";
  btn.title = "Preset Avatar";

  const img = document.createElement("img");
  img.src = PRESET_URL;
  img.alt = "Preset Avatar";
  img.crossOrigin = "anonymous";

  btn.appendChild(img);
  presetsContainer.appendChild(btn);

  // Preload the image
  const image = new Image();
  image.crossOrigin = "anonymous";
  image.onload = () => {
    inputPreview.src = PRESET_URL;
    inputPreview.style.display = "block";
    inputPlaceholder.style.display = "none";

    activeImage = image;
    renderAvatar(image);
  };
  image.onerror = () => {
    // Fallback: If CORS fails, try standard load (without anonymous)
    console.warn("Could not load image with anonymous CORS, trying standard loading.");
    
    const fallbackImage = new Image();
    fallbackImage.onload = () => {
      inputPreview.src = PRESET_URL;
      inputPreview.style.display = "block";
      inputPlaceholder.style.display = "none";
      activeImage = fallbackImage;
      renderAvatar(fallbackImage);
    };
    fallbackImage.src = PRESET_URL;
  };
  image.src = PRESET_URL;

  // Click handler
  btn.addEventListener("click", () => {
    document.querySelectorAll(".preset-item").forEach(item => item.classList.remove("active"));
    btn.classList.add("active");
    
    inputPreview.src = PRESET_URL;
    inputPreview.style.display = "block";
    inputPlaceholder.style.display = "none";

    if (activeImage) {
      renderAvatar(activeImage);
    }
  });
}

// Start Presets
initPresets();
updateSliderValues();
